<a href="https://colab.research.google.com/github/tim-parisi/data-science-project/blob/main/data_science_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science Project

Team Members:
Ignacio, Timothy, Jamie, Megan

...

## Data Exploration and Cleaning

In [ ]:
# Libraries
import pandas as pd
import numpy as np

### Dataset A (Crypto Usage)

In [ ]:
# Download dataset
df = pd.read_csv('/content/UK student crypto usage.csv')
df

,Unnamed: 0,Channel,Surevy year,Degree,Degree year,Nationality,Career (Aspiration or current),Crypto type,Crypto usage purpose,Crypto knowledge,Crypto usage duration (years),Trade performance,Remittance amount (%),Crypto knowledge source,Influenced family and friends,Intend to use crypto in future
0,0,online,2022,Business,2nd,Turkey,Medical,BTC,remittance,+++,4-5,NaN,100.0,family,Y,Y
1,1,f2f,2020,STEM,MSc,Europe,Engineering,"BTC,ETH,ALT",trade,+++,1,NaN,NaN,study/research,N,Y
2,2,online,2024,Humanities,Phd,India,Medical,"BTC,ALT","remittance,trans",+++,4-5,NaN,25.0,study/research,N,Y
3,3,online,2021,STEM,2nd,Europe,Finance,DOGE,trade,+++,1,--,NaN,friends,Y,Y
4,4,online,2021,STEM,MSc,USA,Technology,NFT,"trade,remittance,trans",NaN,4-5,++,25.0,family,N,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15805,15805,f2f,2020,Humanities,PhD,Turkey,Retail,ALT,"remittance,trans",++,NaN,NaN,50.0,study/research,Y,N
15806,15806,online,2024,Business,1st,Africa,NaN,"ETH,ALT",trade,+,1-3,NaN,NaN,friends,N,Y
15807,15807,online,2020,Business,MSc,Turkey,Medical,"BTC,NFT",trade,+,1,--,NaN,study/research,Y,N
15808,15808,online,2021,STEM,MSc,China,Engineering,ETH,trade,++,1-3,++,NaN,study/research,Y,Y
15809,15809,f2f,2024,Business,MSc,USA,Retail,"BTC,ETH","trade,remittance,trans",+++,NaN,NaN,25.0,family,Y,Y

In [ ]:
# Get unique values for each column
for name in df.columns:
  unique_values = df[name].unique()
  print(unique_values)

[    0     1     2 ... 15807 15808 15809]
['online' 'f2f']
[2022 2020 2024 2021 2023]
['Business' 'STEM' 'Humanities']
['2nd' 'MSc' 'Phd' 'PhD' '3rd' '1st']
['Turkey' 'Europe' 'India' 'USA' 'Africa' 'ME' 'China' 'South America'
 'UK']
['Medical' 'Engineering' 'Finance' 'Technology' nan 'Public' 'Retail'
 'Legal']
['BTC' 'BTC,ETH,ALT' 'BTC,ALT' 'DOGE' 'NFT' 'ALT' 'BTC,ETH' 'BTC,NFT,DOGE'
 'ETH,ALT' 'NFT,ALT' nan 'BTC,ETH,NFT' 'BTC,NFT' 'ETH' 'BTC,NFT,ALT'
 'BTC,DOGE' 'ETH,NFT,ALT' 'ETH,DOGE']
['remittance' 'trade' 'remittance,trans' 'trade,remittance,trans'
 'trade,remittance']
['+++' nan '+' '++']
['4-5' '1' '1-3' '5+' '11' nan '11-3' '1-31-3']
[nan '--' '++' '+++' '-' '+']
[100.  nan  25.  50.  75.]
['family' 'study/research' 'friends' 'marketing']
['Y' 'N']
['Y' 'N']

### Dataset B (Student Engagement)

In [ ]:
# Download dataset
df = pd.read_csv('/content/UK online student engagement.csv')
df

,Unnamed: 0,External,Year,session 1,session 2,test 1,session 3,session 4,test 2,session 5,test 3,session 6,ind cw,group cw,final grade,fourm Q,fourm A,office hour visits,droupout
0,0,N,third,13,20,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,Y
1,1,N,third,71,77,A,40.0,67.0,A,69.0,A,41.0,A,A,D,13,4,4,N
2,2,Y,first,32,62,F,76.0,77.0,A,35.0,F,93.0,F,F,B,16,9,3,N
3,3,Y,first,8,4,F,46.0,36.0,C,93.0,B,79.0,A,D,B,22,4,6,N
4,4,Y,first,6,1,F,23.0,33.0,D,90.0,C,82.0,C,A,C,19,9,7,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11244,11244,Y,second,7,30,D,4.0,35.0,F,28.0,B,91.0,D,D,F,19,7,4,N
11245,11245,Y,third,59,63,A,90.0,40.0,A,57.0,F,93.0,D,C,A,13,6,5,N
11246,11246,Y,third,25,59,C,82.0,33.0,F,77.0,B,56.0,B,F,A,12,9,5,N
11247,11247,N,third,12,13,D,40.0,43.0,D,57.0,B,23.0,D,C,D,12,6,6,N
11248,11248,Y,third,97,28,C,52.0,22.0,C,93.0,A,65.0,F,C,A,8,2,6,N